api:
    resource: ../../src/Controller/Api/
    prefix: /api
    name_prefix: api.
    trailing_slash_on_root: false
    type: annotation

controllers:
    resource: ../../src/Controller/
    type: annotation
