knpu_oauth2_client:
    clients:
        facebook_main:
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            redirect_route: oauth.facebook_check
            redirect_params: {}
            graph_api_version: v2.12
